#! /bin/bash

TEST=../../../tools/throughput_test.py


# Short test
${TEST} --cpu-limits "200,100,50" --router-threads  "1,2"  --sender-threads "1,2"

# Full test
#${TEST} --cpu-limits "500,400,300,200,100,50,25" --router-threads  "1,2,4,5,7,10"  --sender-threads "1,2,5,10"


