#! /bin/bash


#----------------------------------------------------------
# Begin user-settable parameters 
#----------------------------------------------------------

# Set this based on which version of the Router software you have installed.
ROUTER_VERSION=3.4.1

# And set this to which test you want to run.
TEST=throughput

# How long should each test last?
# I tried 60 seconds, and they were indistinguishable from 15 seconds
# with respect to stability of results.
DURATION=15

# Each graphed result will the the average of several identically 
# configured tests, the number controlled by this variable.
ITERATIONS="1 2 3"

# The CPU allocation for each router during the tests.
#CPU_LIMITS="400 300 200 100 50 25"
CPU_LIMITS="300 200 100"


#ROUTER_THREADS="1 2 4 5 8"
ROUTER_THREADS="2 4 5"

#SENDER_THREADS="1 2 5 10"
SENDER_THREADS="1 2 5"


#----------------------------------------------------------
# End user-settable parameters 
#----------------------------------------------------------


RESULT_ROOT=../../../results/${ROUTER_VERSION}/${TEST}
TEST_RESULTS_DIR=../../../results/${ROUTER_VERSION}/${TEST}/test_results
echo "TEST_RESULTS_DIR == ${TEST_RESULTS_DIR}"

mkdir -p ${RESULT_ROOT}/test_results
mkdir -p ${RESULT_ROOT}/data
mkdir -p ${RESULT_ROOT}/graphs
mkdir -p ${RESULT_ROOT}/routers


# Your router is installed in the standard place.
ROUTER=/usr/local/sbin/skrouterd


echo "Starting routers from ${ROUTER}"
date

for RT in ${ROUTER_THREADS} ; do
  echo "==========================================================="
  echo "Router threads ${RT} "
  echo "==========================================================="
  # Create the router config files
  sed "s/N_THREADS/${RT}/"   < A.conf.template    > A.conf
  sed "s/N_THREADS/${RT}/"   < B.conf.template    > B.conf


  for CPU in ${CPU_LIMITS} ; do

    echo "==========================================================="
    echo "CPU ${CPU} "
    echo "==========================================================="

    # Start Router A --------------------------------
    # I don't want to constrain memory
    #systemd-run --quiet --user --scope -p CPUQuota=${CPU}% -p MemoryMax=4G ${ROUTER} --config ./A.conf > router.log 2>&1 &
    systemd-run --quiet --user --scope -p CPUQuota=${CPU}% ${ROUTER} --config ./A.conf > ${RESULT_ROOT}/routers/A.log 2>&1 &
    echo "Router A started"
    sleep 5
    
    # Start Router B --------------------------------
    systemd-run --quiet --user --scope -p CPUQuota=${CPU}% ${ROUTER} --config ./B.conf > ${RESULT_ROOT}/routers/B.log 2>&1 &
    ROUTER_B_PID=$!
    echo "Router B started with PID ${ROUTER_PID}"
    
    # Give plenty of time for the routers to set up the network
    sleep 10
    

    
    # Start the server. This is only done once.
    iperf3 -s -p 5801 &
    SERVER_PID=$!
    echo "server started"
    
    
    
    for ST in ${SENDER_THREADS}; do
      echo "==========================================================="
      echo "sender threads ${ST} "
      echo "==========================================================="
      sleep 1
      for ITERATION in ${ITERATIONS}; do 
        echo " "
        echo " "
        echo "----------------------------------"
        echo "iteration ${ITERATION}"
        echo "----------------------------------"
        RESULT_NAME="cpu_${CPU}_sender-threads_${ST}_router-threads_${RT}_iteration_${ITERATION}"
    
        # Run the client
        iperf3 -c 127.0.0.1 -p 5800 -P ${ST} -t ${DURATION} > ${TEST_RESULTS_DIR}/${RESULT_NAME}
        echo " "
        echo "threads ${THREADS} iteration ${ITERATION} complete"
        sleep 5
      done
    done
    
    sleep 5
    echo " "
    echo "killing server at PID ${SERVER_PID}"
    kill -9 ${SERVER_PID}
    echo "killing routers..."
    pkill skrouterd
    sleep 2
    pkill skrouterd
    sleep 2
    echo "Any routers remaining?"
    ps -aef | grep skrouterd | grep -v grep
    echo " "
    echo " "
    echo " "
  done
done
date

echo "\n\n\n======================================="
echo "Running results post-processing"
echo "=======================================\n\n\n"
sleep 10

./process_results.py ${ROUTER_VERSION}


echo "\n\ndone\n\n\n"


