#! /bin/bash

pkill iperf3

PORT=5801
DURATION=30
THREADS_SETTINGS="1 2 3 4 5 6 7 8 9 10 12 14 16 18 20"
ITERATIONS="1 2 3 4 5"

TEST_NAME=throughput

RESULTS_DIR=../../../results/iperf/throughput/test_results
mkdir -p ${RESULTS_DIR}


# Start the server -- one for all tests
iperf3 -s -p ${PORT} &
SERVER_PID=$!
echo "server started with PID ${SERVER_PID}"


# Run each client and capture output
for ITERATION in ${ITERATIONS}; do 
  for N_THREADS in ${THREADS_SETTINGS}; do
      RESULT_NAME="threads_${N_THREADS}_iteration_${ITERATION}"
      RESULT_PATH=${RESULTS_DIR}/${RESULT_NAME}
      echo "iteration: ${ITERATION} threads: ${N_THREADS}s"
      iperf3 -c 127.0.0.1 -p ${PORT} -P ${N_THREADS} -t ${DURATION} > ${RESULT_PATH}
      echo " "
      echo "test with ${N_THREADS} threads complete"
      sleep 5
  done
done

sleep 5
echo " "
echo "killing server at PID == ${SERVER_PID}"
kill -9 ${SERVER_PID}
echo " "
echo "done running test"
echo " "
echo " "
echo "processing results..."
