#! /bin/bash

DURATION=60

echo "Test duration is ${DURATION} seconds."
sleep 5

DATE=`date +"%Y_%m_%d_%H%M"`

# Make the output directory, and define output files -------------
OUTPUT_DIR=../runs/${DATE}
mkdir ${OUTPUT_DIR}
ROUTER_OUTPUT=${OUTPUT_DIR}/router
IPERF_RECV_OUTPUT=${OUTPUT_DIR}/iperf_recv
IPERF_SEND_OUTPUT=${OUTPUT_DIR}/iperf_send
SOCKPERF_RECV_OUTPUT=${OUTPUT_DIR}/sockperf_recv
SOCKPERF_SEND_OUTPUT=${OUTPUT_DIR}/sockperf_send

# Store information about the system.
cat /proc/cpuinfo > ${OUTPUT_DIR}/cpuinfo
cat /proc/meminfo > ${OUTPUT_DIR}/meminfo

# Start the router ------------------------------
source ../../../utils/set_up_environment

${ROUTER} --config ./skrouterd.conf > ${ROUTER_OUTPUT} 2>&1  &
ROUTER_PID=$!
echo "Router has started with PID ${ROUTER_PID}"

sleep 3

# Start the receivers ---------------------------
iperf3 -s -p 5802                       > ${IPERF_RECV_OUTPUT}     2>&1  &
IPERF_RECV_PID=$!
sockperf sr -i 127.0.0.1 -p 5804 --tcp  > ${SOCKPERF_RECV_OUTPUT}  2>&1  &
SOCKPERF_RECV_PID=$!
echo "Receivers have started."

sleep 3

# Start the senders -----------------------------------
iperf3 -c 127.0.0.1 -p 5801 -t ${DURATION} -P 1 > ${IPERF_SEND_OUTPUT} 2>&1  &
IPERF_SEND_PID=$!
sockperf pp -i 127.0.0.1 -p 5803 --tcp -m 100 -t ${DURATION} --mps=max > ${SOCKPERF_SEND_OUTPUT} 2>&1  &
SOCKPERF_SEND_PID=$!
echo -n "Senders started at time: "
date
echo "Test duration is ${DURATION}."


# Wait for the senders to finish. -----------------------------------
wait ${IPERF_SEND_PID}
echo "Iperf sender has terminated."
wait ${SOCKPERF_SEND_PID}
echo "Sockperf sender has terminated."


# Shut everything down --------------------------
echo "Shutting down."
kill -15 ${ROUTER_PID}
kill -15 ${IPERF_RECV_PID}
kill -15 ${SOCKPERF_RECV_PID}


# Process the output into a graph.
./process_output  ${DATE}

