#! /bin/bash

DURATION=60

echo "test: Throughput"
echo "Test duration is ${DURATION} seconds."
sleep 5

DATE=`date +"%Y_%m_%d_%H%M"`

# Make the output directory, and define output files -------------
OUTPUT_DIR=../runs/${DATE}
mkdir ${OUTPUT_DIR}
ROUTER_OUTPUT=${OUTPUT_DIR}/router
IPERF_RECV_OUTPUT=${OUTPUT_DIR}/iperf_recv
IPERF_SEND_OUTPUT=${OUTPUT_DIR}/iperf_send

# Store information about the system.
cat /proc/cpuinfo > ${OUTPUT_DIR}/cpuinfo
cat /proc/meminfo > ${OUTPUT_DIR}/meminfo

# Start the router ------------------------------
source ../../../utils/set_up_environment

${ROUTER} --config ./skrouterd.conf > ${ROUTER_OUTPUT} 2>&1  &
ROUTER_PID=$!
echo "Router has started with PID ${ROUTER_PID}"
sleep 3

# Start the receiver ---------------------------
iperf3 -s -p 5802 > ${IPERF_RECV_OUTPUT}     2>&1  &
IPERF_RECV_PID=$!
sleep 3

# Start the sender -----------------------------------
iperf3 -c 127.0.0.1 -p 5801 -t ${DURATION} -P 1 > ${IPERF_SEND_OUTPUT}     2>&1  &
IPERF_SEND_PID=$!
echo -n "Sender started at time: "
date
echo "Test duration is ${DURATION}."

# Wait for the sender to finish. -----------------------------------
wait ${IPERF_SEND_PID}
echo "Iperf sender has terminated."

# Shut everything down --------------------------
echo "Shutting down."
kill -15 ${ROUTER_PID}
kill -15 ${IPERF_RECV_PID}


# Process output into resuting graph -------------------------------
./process_output ${DATE}

